### ISSUE TITLE
Repository not linked to npm

### ISSUE THREAD

**Issue by CREEATION** [DanElliottPalmer/gimp-palette-parser#1]
=> https://www.npmjs.com/package/gimp-palette-parser

**Comment by DanElliottPalmer** [comment]
hey @CREEATION ive updated the package json to contain the changes. do you know if i need to do a publish for them to appear on the npm site?

**Comment by CREEATION** [comment]
Hey! Yeah, I think you have to publish again with a new version number.
Good news is I'm creating a new pull request in a minute with a few fixes, so you can bump the version number and publish after the merge 🐢

**Comment by DanElliottPalmer** [comment]
merged in your branch, bumped the version a patch and published. looks like npm is now displaying the github info. cheers for your help 👍
